# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 19) do

  create_table "accounts", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "sponsor_id",                :integer
    t.column "admin",                     :boolean,                :default => false
    t.column "main_picture_id",           :integer
  end

  create_table "accounts_groups", :id => false, :force => true do |t|
    t.column "account_id", :integer
    t.column "group_id",   :integer
  end

  create_table "friendships", :force => true do |t|
    t.column "account_id",  :integer
    t.column "friend_id",   :integer
    t.column "status",      :string
    t.column "created_at",  :datetime
    t.column "accepted_at", :datetime
    t.column "updated_at",  :datetime
  end

  create_table "globalize_countries", :force => true do |t|
    t.column "code",                   :string, :limit => 2
    t.column "english_name",           :string
    t.column "date_format",            :string
    t.column "currency_format",        :string
    t.column "currency_code",          :string, :limit => 3
    t.column "thousands_sep",          :string, :limit => 2
    t.column "decimal_sep",            :string, :limit => 2
    t.column "currency_decimal_sep",   :string, :limit => 2
    t.column "number_grouping_scheme", :string
  end

  add_index "globalize_countries", ["code"], :name => "index_globalize_countries_on_code"

  create_table "globalize_languages", :force => true do |t|
    t.column "iso_639_1",             :string,  :limit => 2
    t.column "iso_639_2",             :string,  :limit => 3
    t.column "iso_639_3",             :string,  :limit => 3
    t.column "rfc_3066",              :string
    t.column "english_name",          :string
    t.column "english_name_locale",   :string
    t.column "english_name_modifier", :string
    t.column "native_name",           :string
    t.column "native_name_locale",    :string
    t.column "native_name_modifier",  :string
    t.column "macro_language",        :boolean
    t.column "direction",             :string
    t.column "pluralization",         :string
    t.column "scope",                 :string,  :limit => 1
  end

  add_index "globalize_languages", ["iso_639_1"], :name => "index_globalize_languages_on_iso_639_1"
  add_index "globalize_languages", ["iso_639_2"], :name => "index_globalize_languages_on_iso_639_2"
  add_index "globalize_languages", ["iso_639_3"], :name => "index_globalize_languages_on_iso_639_3"
  add_index "globalize_languages", ["rfc_3066"], :name => "index_globalize_languages_on_rfc_3066"

  create_table "globalize_translations", :force => true do |t|
    t.column "type",                :string
    t.column "tr_key",              :string
    t.column "table_name",          :string
    t.column "item_id",             :integer
    t.column "facet",               :string
    t.column "built_in",            :boolean, :default => true
    t.column "language_id",         :integer
    t.column "pluralization_index", :integer
    t.column "text",                :text
    t.column "namespace",           :string
  end

  add_index "globalize_translations", ["tr_key", "language_id"], :name => "index_globalize_translations_on_tr_key_and_language_id"
  add_index "globalize_translations", ["table_name", "item_id", "language_id"], :name => "globalize_translations_table_name_and_item_and_language"

  create_table "groups", :force => true do |t|
    t.column "title",        :string
    t.column "moderator_id", :integer
    t.column "type",         :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "invitations", :force => true do |t|
    t.column "account_id",         :integer
    t.column "email",              :string
    t.column "invitation_token",   :string
    t.column "created_at",         :datetime
    t.column "updated_at",         :datetime
    t.column "invited_account_id", :integer
  end

  create_table "login_infos", :force => true do |t|
    t.column "account_id", :integer
    t.column "header",     :text
  end

  create_table "messages", :force => true do |t|
    t.column "subject",      :string
    t.column "body",         :string
    t.column "sender_id",    :integer
    t.column "recipient_id", :integer
    t.column "read",         :boolean
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "parent_id",    :integer
    t.column "status_id",    :integer
  end

  create_table "pictures", :force => true do |t|
    t.column "account_id",    :integer
    t.column "name",          :string
    t.column "approved",      :boolean
    t.column "x_rated",       :boolean
    t.column "parent_id",     :integer
    t.column "content_type",  :string
    t.column "filename",      :string
    t.column "thumbnail",     :string
    t.column "size",          :integer
    t.column "width",         :integer
    t.column "height",        :integer
    t.column "approved_at",   :date
    t.column "approved_from", :integer
    t.column "album_id",      :integer
  end

  create_table "preferences", :force => true do |t|
    t.column "sex",        :integer
    t.column "oral",       :integer
    t.column "anal",       :integer
    t.column "ns",         :integer
    t.column "kv",         :integer
    t.column "sm",         :integer
    t.column "dom",        :integer
    t.column "dev",        :integer
    t.column "rp",         :integer
    t.column "lingerie",   :integer
    t.column "tools",      :integer
    t.column "voyeur",     :integer
    t.column "exhib",      :integer
    t.column "nymph",      :integer
    t.column "bizare",     :integer
    t.column "outdoor",    :integer
    t.column "adventure",  :integer
    t.column "parking",    :integer
    t.column "cinema",     :integer
    t.column "clubs",      :integer
    t.column "sauna",      :integer
    t.column "account_id", :integer
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "specs", :force => true do |t|
    t.column "account_id",      :integer
    t.column "birth_date",      :date
    t.column "height",          :integer, :limit => 3, :precision => 3,  :scale => 0
    t.column "weigth",          :integer, :limit => 3, :precision => 3,  :scale => 0
    t.column "body_type",       :string,                                              :default => "n/a"
    t.column "eye_color",       :string,                                              :default => "n/a"
    t.column "hair_color",      :string,                                              :default => "n/a"
    t.column "hair_length",     :string,                                              :default => "n/a"
    t.column "body_hair",       :string,                                              :default => "n/a"
    t.column "pubic_hair",      :string,                                              :default => "n/a"
    t.column "sexuality",       :string,                                              :default => "n/a"
    t.column "glasses",         :boolean
    t.column "smoker",          :boolean
    t.column "tatoo",           :boolean
    t.column "piercing",        :boolean
    t.column "handicaped",      :boolean
    t.column "stds",            :boolean
    t.column "hiv",             :boolean
    t.column "phantasies",      :string,                                              :default => "n/a"
    t.column "description",     :string,                                              :default => "n/a"
    t.column "zip_code",        :string
    t.column "city",            :string
    t.column "street_adress",   :string
    t.column "latitude",        :decimal,              :precision => 10, :scale => 6, :default => 0.0
    t.column "longitude",       :decimal,              :precision => 10, :scale => 6, :default => 0.0
    t.column "children",        :boolean
    t.column "children_wanted", :boolean
    t.column "breast_cup",      :string,                                              :default => ""
    t.column "gender",          :string
    t.column "penis_length",    :decimal,              :precision => 3,  :scale => 1, :default => 0.0
    t.column "penis_diameter",  :decimal,              :precision => 3,  :scale => 1, :default => 0.0
  end

end
